version: '3.8'

services:
  db:
    image: mysql:latest 
    container_name: db 
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_USER: process.env.DB_USER
      MYSQL_ROOT_PASSWORD: process.env.DB_PASSWORD
      MYSQL_PASSWORD: process.env.DB_PASSWORD
      MYSQL_DATABASE: process.env.DB_NAME 
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - '3307:3306'

volumes:
  my-db:
